---
- name: OpenScap Scan
  hosts: all
  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_pci-dss
    oscap_policy: ssg-rhel8-ds
    scanns_home: /tmp/work

  tasks:

  - name: Install openscap scanner
    yum:
      name: 
        - openscap-scanner
        - scap-security-guide
      state: latest
  
  - block:
    - name: Run Scann on vms
      ignore_errors: true
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/oscap-arf.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml
    
    - debug:
        msg: scanning....

    always:
    - name: Download report
      fetch:
        src: /tmp/oscap-report.html
        dest: "{{scanns_home}}/{{ inventory_hostname }}.html"
        flat: yes
        validate_checksum: true