---

- name: registering system
  redhat_subscription:
          state: present
          username: "{{ rhn }}"
          password: "{{ password }}"
  ignore_errors: true
  tags:
          - "register"


- name: Attaching system for the ansible angige pool
  shell: |
          pool=$(subscription-manager list --available --matches='*Ansible Engine' | awk '/(Pool ID)|(ID de grupo)/ {print $NF}' | head -n 1)
          subscription-manager attach --pool=$pool
  ignore_errors: true
  tags:
          - "attach"


- name: Disable all RHSM repos
  rhsm_repository:
          name: '*'
          state: disabled
  tags:
          - "disable"

- name: Enable Ansible Engine Repos
  rhsm_repository:
          name: 
               - rhel-7-server-ansible-2.6-rpms
               - rhel-7-server-rpms
          state: enabled
  tags:
          - "enable"
